blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/fireayehu/chapa-nodejs#readme
    about: Check the documentation for usage examples
  - name: Chapa API Documentation
    url: https://developer.chapa.co/docs
    about: Official Chapa API documentation
